### ISSUE TITLE
Variable assignment error

### ISSUE THREAD

**Issue by markb729** [kohyamat/massgenotyping#1]
Hi,

I've been testing your project using both the supplied sample data and some of my own data. The sample data works fine. However, using my on data (**single** sample with 28 SSR primer pairs) I've come across an issue that I cannot resolve. The error occurs using a python env running python 3.6 (or 3.7) with mgt installed using pip3.

mgt allele-check ./project --force-no-visual-check

Processing D2S1326_filtered.fasta.gz (Wed Sep 23 11:00:22 2020): 

> Traceback (most recent call last):
>   File "/mnt/software/anaconda/envs/mg4/bin/mgt", line 8, in <module>
>     sys.exit(main())
>   File "/mnt/software/anaconda/envs/mg4/lib/python3.6/site-packages/massgenotyping/__init__.py", line 31, in main
>     allele_check.main(args)
>   File "/mnt/software/anaconda/envs/mg4/lib/python3.6/site-packages/massgenotyping/allele_check.py", line 799, in main
>     ach.run()
>   File "/mnt/software/anaconda/envs/mg4/lib/python3.6/site-packages/massgenotyping/allele_check.py", line 267, in run
>     self.tree = construct_tree(self.align, self.ssr_regions, self.motifs)
>   File "/mnt/software/anaconda/envs/mg4/lib/python3.6/site-packages/massgenotyping/allele_check.py", line 659, in construct_tree
>     return constructor.upgma(dmat)
>   File "/mnt/software/anaconda/envs/mg4/lib/python3.6/site-packages/Bio/Phylo/TreeConstruction.py", line 701, in upgma
>     inner_clade.branch_length = 0
> UnboundLocalError: local variable 'inner_clade' referenced before assignment

Other iterations to supply the working directory as ./project/D1S550 or ./project/D1S550/D1S550_filtered.fasta.gz also fail _but do not generate an error message_ (blast output is absent). I have considered that since I have only a single sample (i.e. one set of fastq reads), an exception occurs. In other words, the routine is not designed to process only a single sample. If so, fine. I just wanted to check with you before I delve into this a little deeper.

**Comment by kohyamat** [comment]
Hi,

Thank you for pointing out the issue. That seems to be due to that you only have a single sample and there is no variation in sequences.

I fixed this issue in the branch iss1. Could you reinstall the package as follows and try the command again?

```
pip3 uninstall massgenotyping
pip3 install git+https://github.com/kohyamat/massgenotyping@iss1
```

**Comment by markb729** [comment]
Hi Tetsuo,

Your fix solves the exception - thank you very much.
